# GENERATED by scripts/gen_shims.py -- do not edit by hand.
"""
idpy.PRNGS.CRNGS -> idpy.physics.prngs.CRNGS

Phase 0b compatibility shim, generated from scripts/consumer-symbols.txt.
Kept for `collabs/`, which tracks master unpinned and is not being migrated.
"""

import warnings as _warnings
from importlib import import_module as _import_module

_OLD = 'idpy.PRNGS.CRNGS'
_NEW = 'idpy.physics.prngs.CRNGS'

# What scripts/consumer-symbols.txt records at this path.
_MOVED = frozenset((
    'CRNGS',
    'F_GaussianCosSingle',
    'F_Norm',
    'F_RandomIntegerUnbiasedLemire',
    '_codify_CRNGS',
    '_codify_CRNGS_list',
    '_codify_MINSTD',
    '_codify_MINSTD32',
    '_codify_MMIX',
    '_codify_NUMREC',
    '_codify_comment',
    '_codify_declare_MINSTD32_swap',
    '_codify_declare_MINSTD_swap',
    '_codify_flat',
    '_codify_flat_integers_biased',
    '_codify_flat_integers_unbiased',
    '_codify_flat_mean_var',
    '_codify_gaussian_p',
    '_codify_gaussian_seq',
    '_codify_n_random_vars',
    '_codify_newl',
    '_codify_read_seeds',
    '_codify_write_seeds',
))

_warnings.warn(
    f"{_OLD} has moved to {_NEW}. The old path still works and will keep "
    f"working until a re-freeze of scripts/consumer-symbols.txt shows nothing "
    f"importing it; update the import when convenient.",
    FutureWarning, stacklevel=2,
)

# FutureWarning, not DeprecationWarning, and that was measured rather than
# assumed. Python's default filter is `default::DeprecationWarning:__main__`,
# so a DeprecationWarning is shown only when it fires from __main__: a collab
# reaching an old path through one of its own helper .py modules would be told
# nothing at all. idpy's users are researchers in notebooks, which is the case
# Python's own guidance points at FutureWarning for.

# Imported eagerly, and this is a deliberate departure from the brief, which
# asks for the target to be resolved lazily inside __getattr__.
#
# The brief's reason for laziness was an import cycle: a shim living *inside*
# the real package (idpy/Utils/__init__.py re-exporting from idpy.IdpyCode)
# can be re-entered while core is still initialising. Under the layout that
# was actually built, the shim tree and the real tree are disjoint -- shims
# live at src/idpy/<old path>/ and nothing under src/idpy/core/ or
# src/idpy/physics/ imports an old path -- so the shim layer is a strict leaf
# and cannot participate in a cycle.
#
# What laziness *would* cost is the signal both fixtures depend on. Importing
# idpy.CUDA.CUDA on a machine without pycuda has always raised
# ModuleNotFoundError('pycuda'), which check_consumers.py reads to tell "this
# machine lacks a binding" (skip) apart from "a consumer is broken" (fail). A
# lazy shim imports cleanly and defers that error to attribute access, where
# it escapes hasattr() -- which catches only AttributeError -- and takes the
# check down with it. Eager import reproduces the old behaviour exactly.
_target = _import_module(_NEW)


def __getattr__(name):
    # Permissive, because this shim is a leaf: nothing lives underneath it, so
    # there is no submodule to shadow. The fixtures cover `from ... import
    # name` and by design not dotted access, so forwarding only the recorded
    # names would break `IdpyMemory.OnDevice` and everything shaped like it.
    try:
        return getattr(_target, name)
    except AttributeError:
        raise AttributeError(
            f"module {_OLD!r} has no attribute {name!r}") from None


def __dir__():
    return sorted(set(_MOVED) | set(dir(_target)))
