# GENERATED by scripts/gen_shims.py -- do not edit by hand.
"""
idpy.Utils -> idpy.core.utils

Phase 0b compatibility shim, generated from scripts/consumer-symbols.txt.
Kept for `collabs/`, which tracks master unpinned and is not being migrated.
"""

import warnings as _warnings
from importlib import import_module as _import_module

_OLD = 'idpy.Utils'
_NEW = 'idpy.core.utils'

# What scripts/consumer-symbols.txt records at this path.
_MOVED = frozenset((
    # nothing recorded
))

_warnings.warn(
    f"{_OLD} has moved to {_NEW}. The old path still works and will keep "
    f"working until a re-freeze of scripts/consumer-symbols.txt shows nothing "
    f"importing it; update the import when convenient.",
    FutureWarning, stacklevel=2,
)

# FutureWarning, not DeprecationWarning, and that was measured rather than
# assumed. Python's default filter is `default::DeprecationWarning:__main__`,
# so a DeprecationWarning is shown only when it fires from __main__: a collab
# reaching an old path through one of its own helper .py modules would be told
# nothing at all. idpy's users are researchers in notebooks, which is the case
# Python's own guidance points at FutureWarning for.

# Imported eagerly, and this is a deliberate departure from the brief, which
# asks for the target to be resolved lazily inside __getattr__.
#
# The brief's reason for laziness was an import cycle: a shim living *inside*
# the real package (idpy/Utils/__init__.py re-exporting from idpy.IdpyCode)
# can be re-entered while core is still initialising. Under the layout that
# was actually built, the shim tree and the real tree are disjoint -- shims
# live at src/idpy/<old path>/ and nothing under src/idpy/core/ or
# src/idpy/physics/ imports an old path -- so the shim layer is a strict leaf
# and cannot participate in a cycle.
#
# What laziness *would* cost is the signal both fixtures depend on. Importing
# idpy.CUDA.CUDA on a machine without pycuda has always raised
# ModuleNotFoundError('pycuda'), which check_consumers.py reads to tell "this
# machine lacks a binding" (skip) apart from "a consumer is broken" (fail). A
# lazy shim imports cleanly and defers that error to attribute access, where
# it escapes hasattr() -- which catches only AttributeError -- and takes the
# check down with it. Eager import reproduces the old behaviour exactly.
_target = _import_module(_NEW)


def __getattr__(name):
    # Strict, because this shim is a package. See __getattr__ in
    # scripts/gen_shims.py for why answering every name would shadow the real
    # submodules underneath, silently and with nothing raised to notice.
    if name not in _MOVED:
        raise AttributeError(f"module {_OLD!r} has no attribute {name!r}")
    return getattr(_target, name)


def __dir__():
    return sorted(set(_MOVED) | set(dir(_target)))
