#!/usr/bin/env python3
"""
Generate the Phase 0b compatibility shims from the frozen consumer fixtures.

The restructure moved every module: idpy/LBM/LBM.py is now
src/idpy/physics/lbm/LBM.py, and so on for 77 files. `collabs/` -- roughly
eighty directories, unpinned, tracking master, with live simulations running
against them -- is not being migrated in this pass. So every old dotted path
has to keep working.

**Generated, not hand-written.** scripts/consumer-symbols.txt is
`module <TAB> symbol <TAB> count`, which is already a shim specification: it
says exactly which names must remain reachable at exactly which old paths.
Forty-six hand-maintained shim modules would drift away from that file the
first time anything moved; a generator plus the fixture cannot. Regenerate
with:

    python3 scripts/gen_shims.py            # write src/idpy/<old paths>/
    python3 scripts/gen_shims.py --check    # verify what is committed matches

Note that the shims exist for `collabs/`, NOT for the paper repositories. The
papers never install idpy -- they do sys.path.append("../../") and reach into a
checkout -- so a shim inside the installed package cannot reach them. They are
migrated to the new paths instead. See docs/phase0b-brief.md.

Three design points below were established by testing, and one departs from
the brief; each is argued where it is implemented.
"""

import argparse
import importlib
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SRC = REPO / 'src' / 'idpy'
SURFACE = REPO / 'scripts' / 'consumer-surface.txt'
SYMBOLS = REPO / 'scripts' / 'consumer-symbols.txt'

# The restructure, as a dotted-path mapping. This is the single source of truth
# for where everything went: the one-shot source rewrite used it, the shims are
# generated from it, and scripts/check_layering.py checks the layers it defines.
#
# Backends map to packages rather than to the single modules STRATEGY.md's
# migration table names (core/backends/cuda.py). That row cannot be implemented
# as written: the package __init__ holds only the language token and is always
# importable, while the implementation module imports pycuda/pyopencl/
# pymetallic and is importable only where the binding exists. idpy.core needs
# the four tokens eagerly to build idpy_langs_sys, and takes the four
# implementations only behind an AreModulesThere guard. Collapsing the two
# would put `import pycuda` on the eager path and break `import idpy.core` on
# every machine without a GPU binding -- which includes CI and most laptops.
MAP = {
    'idpy.IdpyCode':       'idpy.core',
    'idpy.Utils':          'idpy.core.utils',
    'idpy.CUDA.CUDA':      'idpy.core.backends.cuda.backend',
    'idpy.CUDA':           'idpy.core.backends.cuda',
    'idpy.OpenCL.OpenCL':  'idpy.core.backends.opencl.backend',
    'idpy.OpenCL':         'idpy.core.backends.opencl',
    'idpy.CTypes.CTypes':  'idpy.core.backends.ctypes_backend.backend',
    'idpy.CTypes':         'idpy.core.backends.ctypes_backend',
    'idpy.Metal.MetalIO':  'idpy.core.backends.metal.io',
    'idpy.Metal.Metal':    'idpy.core.backends.metal.backend',
    'idpy.Metal':          'idpy.core.backends.metal',
    'idpy.LBM':            'idpy.physics.lbm',
    'idpy.IdpyStencils':   'idpy.physics.stencils',
    'idpy.SpinNetworks':   'idpy.physics.spin_networks',
    'idpy.PRNGS':          'idpy.physics.prngs',
}

BANNER = "# GENERATED by scripts/gen_shims.py -- do not edit by hand.\n"


def translate(old):
    """Old dotted path -> new dotted path, longest matching prefix wins."""
    for prefix in sorted(MAP, key=len, reverse=True):
        if old == prefix:
            return MAP[prefix]
        if old.startswith(prefix + '.'):
            return MAP[prefix] + old[len(prefix):]
    raise KeyError(f"no mapping covers {old!r}")


def fixture_modules():
    """Every old module path both fixtures require to stay importable."""
    mods = set()
    for path in (SURFACE, SYMBOLS):
        for line in path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            mods.add(line.lstrip('!').split('\t')[0])
    mods.discard('idpy')          # the real package root, not a shim
    return mods


def fixture_symbols():
    """
    {old module: {symbol}}, excluding the grandfathered breakages.

    A leading `!` marks a pair that was ALREADY unreachable when the fixture
    was frozen -- idpy.Utils.IdpyHardware, idpy.LBM.Equilibria.Equilibria and
    IdpyUnroll._get_single_neighbor_pos_in_code_out_sym. Those must stay
    unreachable: --check-symbols reports them every run as debt that predates
    this work, and a shim that quietly resolved one would erase the record
    while looking like an improvement. They predate Phase 0b and are not its
    to fix.
    """
    out = {}
    for line in SYMBOLS.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#') or line.startswith('!'):
            continue
        parts = line.split('\t')
        if len(parts) < 2:
            continue
        out.setdefault(parts[0], set()).add(parts[1])
    return out


def plan():
    """
    [(old module, new module, is_package, sorted symbols)] for every shim.

    Ancestors are filled in because the fixtures record leaves: they list
    idpy.CUDA.CUDA but never idpy.CUDA, and a module cannot be imported
    through a package that does not exist.
    """
    modules = fixture_modules()
    for m in list(modules):
        parts = m.split('.')
        for i in range(2, len(parts)):
            modules.add('.'.join(parts[:i]))

    symbols = fixture_symbols()
    packages = {m for m in modules
                if any(o.startswith(m + '.') for o in modules)}

    # A recorded name that is really a SUBMODULE, not an attribute, must be
    # left to the import system. `from idpy.IdpyCode import IdpyMemory` -- 92
    # consumers, the single submodule pair among the 277 -- resolves because
    # CPython falls back to importing pkg.name when getattr fails. If the
    # package shim answered that name from __getattr__ instead, the consumer
    # would silently receive whatever attribute happened to match rather than
    # the module, so we generate a shim module at the child path and drop the
    # name from the parent's table. This is why __getattr__ must raise
    # AttributeError for names it does not know (brief, point 2): answering
    # every name shadows every real submodule, and does it silently.
    promoted = set()
    for old in sorted(modules):
        for sym in sorted(symbols.get(old, ())):
            child = f"{old}.{sym}"
            if child in modules:
                continue
            try:
                importlib.import_module(translate(child))
            except ImportError:
                continue                       # a plain attribute, as assumed
            promoted.add(child)
    if promoted:
        modules |= promoted
        packages |= {m for m in modules
                     if any(o.startswith(m + '.') for o in modules)}

    rows = []
    for old in sorted(modules):
        syms = set(symbols.get(old, ()))
        syms -= {s for s in syms if f"{old}.{s}" in modules}
        rows.append((old, translate(old), old in packages, sorted(syms)))
    return rows


def render(old, new, is_package, symbols):
    """
    The text of one shim module.

    Packages and leaf modules get different __getattr__ rules, and the
    difference is not cosmetic.

    A *package* shim answers only the names the fixture records. It has real
    submodules underneath it, and `from pkg import sub` consults __getattr__
    before the import system: a package shim that answered every name would
    return its own object instead of the module, silently. It would also make
    the result depend on import order -- getattr(idpy.core.utils, 'ManageData')
    succeeds or fails according to whether something imported that submodule
    first, so the same code would sometimes get the shim (with its warning) and
    sometimes the real module (without).

    A *leaf* shim forwards anything its target has. Nothing lives underneath
    it, so there is no submodule to shadow and no ordering to depend on, and
    strictness there buys nothing while costing real compatibility: the
    fixtures record `from idpy... import name`, and by design do not cover
    dotted access like `IdpyMemory.OnDevice` -- which is how
    arXiv-2112.02574 reaches OnDevice, and which a strict leaf shim broke.

    _MOVED stays on both: for a package it is the rule, for a leaf it is the
    subset the fixtures actively verify.
    """
    listed = '\n'.join(f"    {s!r}," for s in symbols) or "    # nothing recorded"
    if is_package:
        lookup = '''    # Strict, because this shim is a package. See __getattr__ in
    # scripts/gen_shims.py for why answering every name would shadow the real
    # submodules underneath, silently and with nothing raised to notice.
    if name not in _MOVED:
        raise AttributeError(f"module {_OLD!r} has no attribute {name!r}")
    return getattr(_target, name)'''
    else:
        lookup = '''    # Permissive, because this shim is a leaf: nothing lives underneath it, so
    # there is no submodule to shadow. The fixtures cover `from ... import
    # name` and by design not dotted access, so forwarding only the recorded
    # names would break `IdpyMemory.OnDevice` and everything shaped like it.
    try:
        return getattr(_target, name)
    except AttributeError:
        raise AttributeError(
            f"module {_OLD!r} has no attribute {name!r}") from None'''
    return f'''{BANNER}"""
{old} -> {new}

Phase 0b compatibility shim, generated from scripts/consumer-symbols.txt.
Kept for `collabs/`, which tracks master unpinned and is not being migrated.
"""

import warnings as _warnings
from importlib import import_module as _import_module

_OLD = {old!r}
_NEW = {new!r}

# What scripts/consumer-symbols.txt records at this path.
_MOVED = frozenset((
{listed}
))

_warnings.warn(
    f"{{_OLD}} has moved to {{_NEW}}. The old path still works and will keep "
    f"working until a re-freeze of scripts/consumer-symbols.txt shows nothing "
    f"importing it; update the import when convenient.",
    FutureWarning, stacklevel=2,
)

# FutureWarning, not DeprecationWarning, and that was measured rather than
# assumed. Python's default filter is `default::DeprecationWarning:__main__`,
# so a DeprecationWarning is shown only when it fires from __main__: a collab
# reaching an old path through one of its own helper .py modules would be told
# nothing at all. idpy's users are researchers in notebooks, which is the case
# Python's own guidance points at FutureWarning for.

# Imported eagerly, and this is a deliberate departure from the brief, which
# asks for the target to be resolved lazily inside __getattr__.
#
# The brief's reason for laziness was an import cycle: a shim living *inside*
# the real package (idpy/Utils/__init__.py re-exporting from idpy.IdpyCode)
# can be re-entered while core is still initialising. Under the layout that
# was actually built, the shim tree and the real tree are disjoint -- shims
# live at src/idpy/<old path>/ and nothing under src/idpy/core/ or
# src/idpy/physics/ imports an old path -- so the shim layer is a strict leaf
# and cannot participate in a cycle.
#
# What laziness *would* cost is the signal both fixtures depend on. Importing
# idpy.CUDA.CUDA on a machine without pycuda has always raised
# ModuleNotFoundError('pycuda'), which check_consumers.py reads to tell "this
# machine lacks a binding" (skip) apart from "a consumer is broken" (fail). A
# lazy shim imports cleanly and defers that error to attribute access, where
# it escapes hasattr() -- which catches only AttributeError -- and takes the
# check down with it. Eager import reproduces the old behaviour exactly.
_target = _import_module(_NEW)


def __getattr__(name):
{lookup}


def __dir__():
    return sorted(set(_MOVED) | set(dir(_target)))
'''


def paths_for(old, is_package):
    rel = old.split('.')[1:]                   # drop the leading 'idpy'
    base = SRC.joinpath(*rel)
    return base / '__init__.py' if is_package else base.with_suffix('.py')


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true',
                    help='verify the committed shims match the fixtures')
    args = ap.parse_args(argv[1:])

    rows = plan()
    stale = []
    for old, new, is_package, symbols in rows:
        path = paths_for(old, is_package)
        text = render(old, new, is_package, symbols)
        if args.check:
            if not path.is_file() or path.read_text() != text:
                stale.append(path.relative_to(REPO))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)

    # Anything generated earlier and no longer called for is a shim for a path
    # nothing imports. Left behind it would keep a dead path alive and quietly
    # defeat the removal condition, which is a re-freeze showing no old-path
    # entries.
    wanted = {paths_for(o, p) for o, _, p, _ in rows}
    orphans = sorted(
        f for f in SRC.rglob('*.py')
        if f not in wanted
        and f.read_text(errors='ignore').startswith(BANNER)
    )

    if args.check:
        for f in orphans:
            stale.append(f.relative_to(REPO))
        if stale:
            print(f"{len(stale)} shim file(s) do not match the fixtures:\n")
            for f in stale:
                print(f"  {f}")
            print("\nRun: python3 scripts/gen_shims.py")
            return 1
        print(f"{len(rows)} shim module(s) match the fixtures.")
        return 0

    for f in orphans:
        f.unlink()
        print(f"  removed orphan {f.relative_to(REPO)}")

    n_syms = sum(len(s) for *_, s in rows)
    n_pkgs = sum(1 for *_, p, _ in rows if p)
    print(f"generated {len(rows)} shim module(s) "
          f"({n_pkgs} package, {len(rows) - n_pkgs} module) "
          f"re-exporting {n_syms} symbol(s) under {SRC.relative_to(REPO)}/")
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
